---
author: Tyler Davis
title: Project Dataset and Topics
output: html
---

[https://www.baseball-reference.com/teams/CHC/index.shtml]()

Things you plan to investigate using this dataset:

-   Analyzing Cubs Worst year vs their best
-   Best hitter on 2016 World Series team
  - writing a function to find hitting and pitching data
  - writiing a function to find player data over time
-   Cubs Stats from NL East compared to NL Central
- Map out MLB stadiums in interactive leaflet map

Stat 351 topics you plan to cover during the analysis:

<<<<<<< HEAD
1.  web scraping or API use
2.  interactive graphics
3.  use of appropriate and well-chosen graphics
4.  functional programming
=======
1. web scraping or API use
2. list processing
3. use of appropriate and well-chosen graphics
4. functional programming
=======

---

Comments

- what years? Define the parameters of your analysis a bit more precisely. 
- "Worst vs. Best" by overall league performance? Win/loss record? what other measures are relevant?
- Will you consider the best hitter on the 2016 team and their development over time? How will you examine/compare that data? What is the comparison population? What do you want to know?
---

